-- LandSandBoat job ability level/recast adjustments
-- Generated against the current base SQL layout.
-- Apply after your normal SQL import.

START TRANSACTION;

UPDATE `abilities` SET `level` = 55 WHERE `abilityId` = 267 AND `name` = 'blood_rage';
UPDATE `abilities` SET `level` = 65 WHERE `abilityId` = 252 AND `name` = 'restraint';
UPDATE `abilities` SET `level` = 73 WHERE `abilityId` = 323 AND `name` = 'brazen_rush';
UPDATE `abilities` SET `level` = 60 WHERE `abilityId` = 269 AND `name` = 'impetus';
UPDATE `abilities` SET `level` = 67 WHERE `abilityId` = 253 AND `name` = 'perfect_counter';
UPDATE `abilities` SET `level` = 73 WHERE `abilityId` = 324 AND `name` = 'inner_strength';
UPDATE `abilities` SET `level` = 55 WHERE `abilityId` = 270 AND `name` = 'divine_caress';
UPDATE `abilities` SET `level` = 70 WHERE `abilityId` = 271 AND `name` = 'sacrosanctity';
UPDATE `abilities` SET `level` = 73 WHERE `abilityId` = 325 AND `name` = 'asylum';
UPDATE `abilities` SET `level` = 47 WHERE `abilityId` = 254 AND `name` = 'mana_wall';
UPDATE `abilities` SET `level` = 55 WHERE `abilityId` = 388 AND `name` = 'cascade';
UPDATE `abilities` SET `level` = 62 WHERE `abilityId` = 272 AND `name` = 'enmity_douse';
UPDATE `abilities` SET `level` = 68 WHERE `abilityId` = 273 AND `name` = 'manawell';
UPDATE `abilities` SET `level` = 73 WHERE `abilityId` = 326 AND `name` = 'subtle_sorcery';
UPDATE `abilities` SET `level` = 56 WHERE `abilityId` = 274 AND `name` = 'saboteur';
UPDATE `abilities` SET `level` = 63 WHERE `abilityId` = 275 AND `name` = 'spontaneity';
UPDATE `abilities` SET `level` = 73 WHERE `abilityId` = 327 AND `name` = 'stymie';
UPDATE `abilities` SET `level` = 60 WHERE `abilityId` = 228 AND `name` = 'despoil';
UPDATE `abilities` SET `level` = 50 WHERE `abilityId` = 276 AND `name` = 'conspirator';
UPDATE `abilities` SET `level` = 68 WHERE `abilityId` = 321 AND `name` = 'bully';
UPDATE `abilities` SET `level` = 73 WHERE `abilityId` = 328 AND `name` = 'larceny';
UPDATE `abilities` SET `recastTime` = 60 WHERE `abilityId` = 41 AND `name` = 'steal';
UPDATE `abilities` SET `level` = 40 WHERE `abilityId` = 255 AND `name` = 'divine_emblem';
UPDATE `abilities` SET `level` = 45, `recastTime` = 300 WHERE `abilityId` = 158 AND `name` = 'chivalry';
UPDATE `abilities` SET `level` = 50 WHERE `abilityId` = 277 AND `name` = 'sepulcher';
UPDATE `abilities` SET `level` = 60 WHERE `abilityId` = 278 AND `name` = 'palisade';
UPDATE `abilities` SET `level` = 73 WHERE `abilityId` = 329 AND `name` = 'intervene';
UPDATE `abilities` SET `level` = 45 WHERE `abilityId` = 256 AND `name` = 'nether_void';
UPDATE `abilities` SET `level` = 50 WHERE `abilityId` = 279 AND `name` = 'arcane_crest';
UPDATE `abilities` SET `level` = 65 WHERE `abilityId` = 280 AND `name` = 'scarlet_delirium';
UPDATE `abilities` SET `level` = 73 WHERE `abilityId` = 330 AND `name` = 'soul_enslavement';
UPDATE `abilities` SET `level` = 55 WHERE `abilityId` = 281 AND `name` = 'spur';
UPDATE `abilities` SET `level` = 65 WHERE `abilityId` = 282 AND `name` = 'run_wild';
UPDATE `abilities` SET `level` = 73 WHERE `abilityId` = 331 AND `name` = 'unleash';
UPDATE `abilities` SET `level` = 41 WHERE `abilityId` = 283 AND `name` = 'tenuto';
UPDATE `abilities` SET `level` = 66 WHERE `abilityId` = 284 AND `name` = 'marcato';
UPDATE `abilities` SET `level` = 73 WHERE `abilityId` = 332 AND `name` = 'clarion_call';
UPDATE `abilities` SET `level` = 45 WHERE `abilityId` = 257 AND `name` = 'double_shot';
UPDATE `abilities` SET `level` = 60 WHERE `abilityId` = 285 AND `name` = 'bounty_shot';
UPDATE `abilities` SET `level` = 55 WHERE `abilityId` = 286 AND `name` = 'decoy_shot';
UPDATE `abilities` SET `level` = 73 WHERE `abilityId` = 333 AND `name` = 'overkill';
UPDATE `abilities` SET `level` = 62 WHERE `abilityId` = 296 AND `name` = 'mana_cede';
UPDATE `abilities` SET `level` = 73 WHERE `abilityId` = 337 AND `name` = 'astral_conduit';
UPDATE `abilities` SET `level` = 60, `recastTime` = 150 WHERE `abilityId` = 258 AND `name` = 'sengikori';
UPDATE `abilities` SET `level` = 50 WHERE `abilityId` = 287 AND `name` = 'hamanoha';
UPDATE `abilities` SET `level` = 70, `recastTime` = 150 WHERE `abilityId` = 288 AND `name` = 'hagakure';
UPDATE `abilities` SET `level` = 73 WHERE `abilityId` = 334 AND `name` = 'yaegasumi';
UPDATE `abilities` SET `level` = 40 WHERE `abilityId` = 171 AND `name` = 'sange';
UPDATE `abilities` SET `level` = 55, `recastTime` = 120 WHERE `abilityId` = 259 AND `name` = 'futae';
UPDATE `abilities` SET `level` = 60 WHERE `abilityId` = 291 AND `name` = 'issekigan';
UPDATE `abilities` SET `level` = 73 WHERE `abilityId` = 335 AND `name` = 'mikage';
UPDATE `abilities` SET `level` = 50 WHERE `abilityId` = 292 AND `name` = 'dragon_breaker';
UPDATE `abilities` SET `level` = 60 WHERE `abilityId` = 260 AND `name` = 'spirit_jump';
UPDATE `abilities` SET `level` = 70 WHERE `abilityId` = 293 AND `name` = 'soul_jump';
UPDATE `abilities` SET `level` = 73 WHERE `abilityId` = 336 AND `name` = 'fly_high';
UPDATE `abilities` SET `level` = 40 WHERE `abilityId` = 318 AND `name` = 'smiting_breath';
UPDATE `abilities` SET `level` = 40 WHERE `abilityId` = 319 AND `name` = 'restoring_breath';
UPDATE `abilities` SET `level` = 65 WHERE `abilityId` = 295 AND `name` = 'steady_wing';
UPDATE `abilities` SET `level` = 40 WHERE `abilityId` = 175 AND `name` = 'convergence';
UPDATE `abilities` SET `level` = 45 WHERE `abilityId` = 176 AND `name` = 'diffusion';
UPDATE `abilities` SET `level` = 60 WHERE `abilityId` = 297 AND `name` = 'efflux';
UPDATE `abilities` SET `level` = 68 WHERE `abilityId` = 298 AND `name` = 'unbridled_learning';
UPDATE `abilities` SET `level` = 73 WHERE `abilityId` = 338 AND `name` = 'unbridled_wisdom';
UPDATE `abilities` SET `level` = 55 WHERE `abilityId` = 301 AND `name` = 'triple_shot';
UPDATE `abilities` SET `level` = 68, `recastTime` = 300 WHERE `abilityId` = 392 AND `name` = 'crooked_cards';
UPDATE `abilities` SET `level` = 73 WHERE `abilityId` = 339 AND `name` = 'cutting_cards';
UPDATE `abilities` SET `level` = 42 WHERE `abilityId` = 121 AND `name` = 'blitzers_roll';
UPDATE `abilities` SET `level` = 54 WHERE `abilityId` = 119 AND `name` = 'casters_roll';
UPDATE `abilities` SET `level` = 58 WHERE `abilityId` = 120 AND `name` = 'coursers_roll';
UPDATE `abilities` SET `level` = 61 WHERE `abilityId` = 305 AND `name` = 'avengers_roll';
UPDATE `abilities` SET `level` = 64 WHERE `abilityId` = 118 AND `name` = 'bolters_roll';
UPDATE `abilities` SET `level` = 68 WHERE `abilityId` = 303 AND `name` = 'misers_roll';
UPDATE `abilities` SET `level` = 70 WHERE `abilityId` = 122 AND `name` = 'tacticians_roll';
UPDATE `abilities` SET `level` = 72 WHERE `abilityId` = 302 AND `name` = 'allies_roll';
UPDATE `abilities` SET `level` = 75 WHERE `abilityId` = 304 AND `name` = 'companions_roll';
UPDATE `abilities` SET `level` = 50 WHERE `abilityId` = 266 AND `name` = 'tactical_switch';
UPDATE `abilities` SET `level` = 60 WHERE `abilityId` = 309 AND `name` = 'cooldown';
UPDATE `abilities` SET `level` = 73 WHERE `abilityId` = 340 AND `name` = 'heady_artifice';
UPDATE `abilities` SET `level` = 40 WHERE `abilityId` = 238 AND `name` = 'fan_dance';
UPDATE `abilities` SET `level` = 45 WHERE `abilityId` = 261 AND `name` = 'presto';
UPDATE `abilities` SET `level` = 50 WHERE `abilityId` = 312 AND `name` = 'feather_step';
UPDATE `abilities` SET `level` = 52 WHERE `abilityId` = 313 AND `name` = 'striking_flourish';
UPDATE `abilities` SET `level` = 55 WHERE `abilityId` = 237 AND `name` = 'saber_dance';
UPDATE `abilities` SET `level` = 60 WHERE `abilityId` = 239 AND `name` = 'no_foot_rise';
UPDATE `abilities` SET `level` = 65 WHERE `abilityId` = 264 AND `name` = 'climactic_flourish';
UPDATE `abilities` SET `level` = 71 WHERE `abilityId` = 314 AND `name` = 'ternary_flourish';
UPDATE `abilities` SET `level` = 73 WHERE `abilityId` = 341 AND `name` = 'grand_pas';
UPDATE `abilities` SET `level` = 25 WHERE `abilityId` = 265 AND `name` = 'libra';
UPDATE `abilities` SET `level` = 73 WHERE `abilityId` = 342 AND `name` = 'caper_emissarius';
UPDATE `abilities` SET `level` = 60 WHERE `abilityId` = 316 AND `name` = 'perpetuance';
UPDATE `abilities` SET `level` = 60 WHERE `abilityId` = 317 AND `name` = 'immanence';
UPDATE `abilities` SET `level` = 64 WHERE `abilityId` = 240 AND `name` = 'altruism';
UPDATE `abilities` SET `level` = 66 WHERE `abilityId` = 242 AND `name` = 'tranquility';
UPDATE `abilities` SET `level` = 64 WHERE `abilityId` = 241 AND `name` = 'focalization';
UPDATE `abilities` SET `level` = 66 WHERE `abilityId` = 243 AND `name` = 'equanimity';

COMMIT;
